//	HYPE.documents["DePicUI"]
(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName('head')[0]),
            (b = document.createElement('script')),
            (e = l),
            false == !0 && (e = ''),
            (b.type = 'text/javascript'),
            '' != d &&
              ((b.integrity = d), b.setAttribute('crossorigin', 'anonymous')),
            (b.src = e + '/' + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = 'DePicUI.hyperesources',
      f = 'DePicUI',
      g = 'depicui_hype_container';
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName('script'), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b = null != d ? d.indexOf('/depicui_hype_generated_script.js') : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_740F || null != window.HYPE_dtl_740F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? 'HYPE-740.full.min.js' : 'HYPE-740.thin.min.js';
    c = !0 == d ? 'F' : 'T';
    d = d ? '' : '';
    if (
      false == !1 &&
      ((a = k('HYPE_740' + c, 'HYPE_dtl_740' + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k('HYPE_w_740', 'HYPE_wdtl_740', 'HYPE-740.waypoints.min.js', '')),
      false == !0 &&
        (a = a || k('Matter', 'HYPE_pdtl_740', 'HYPE-740.physics.min.js', '')),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = '' + a + '-' + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName('div'), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute('HYP_dn')) {
          var b = 1,
            h = g;
          do g = '' + h + '-' + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        (h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval('(function(){return ' + b[a].source + '})();'));
      } catch (n) {
        window.console && window.console.log(n),
          (e[b[a].name] = function () {});
      }
    c = new window['HYPE_740' + c](
      f,
      g,
      {
        3: {
          p: 1,
          n: 'Name.svg',
          g: '18',
          t: 'image/svg+xml',
        },
        12: {
          p: 1,
          n: 'GreenPaint.svg',
          g: '36',
          t: 'image/svg+xml',
        },
        21: {
          p: 1,
          n: 'GreenFillButton.svg',
          g: '57',
          t: 'image/svg+xml',
        },
        4: {
          p: 1,
          n: 'DrawButton.svg',
          g: '20',
          t: 'image/svg+xml',
        },
        30: {
          p: 1,
          n: 'BlueDrawButton.svg',
          g: '78',
          t: 'image/svg+xml',
        },
        13: {
          p: 1,
          n: 'BluePaint.svg',
          g: '38',
          t: 'image/svg+xml',
        },
        5: {
          p: 1,
          n: 'FillButton.svg',
          g: '22',
          t: 'image/svg+xml',
        },
        22: {
          p: 1,
          n: 'BlueFillButton.svg',
          g: '59',
          t: 'image/svg+xml',
        },
        6: {
          p: 1,
          n: 'EraseButton.svg',
          g: '24',
          t: 'image/svg+xml',
        },
        31: {
          p: 1,
          n: 'BlackDrawButton.svg',
          g: '80',
          t: 'image/svg+xml',
        },
        14: {
          p: 1,
          n: 'PurplePaint.svg',
          g: '40',
          t: 'image/svg+xml',
        },
        7: {
          p: 1,
          n: 'BlackPaint.svg',
          g: '26',
          t: 'image/svg+xml',
        },
        23: {
          p: 1,
          n: 'BlackFillButton.svg',
          g: '61',
          t: 'image/svg+xml',
        },
        8: {
          p: 1,
          n: 'WhitePaint.svg',
          g: '28',
          t: 'image/svg+xml',
        },
        15: {
          p: 1,
          n: 'AboutButton.svg',
          g: '42',
          t: 'image/svg+xml',
        },
        24: {
          p: 1,
          n: 'SelectedEraseButton.svg',
          g: '65',
          t: 'image/svg+xml',
        },
        9: {
          p: 1,
          n: 'RedPaint.svg',
          g: '30',
          t: 'image/svg+xml',
        },
        16: {
          p: 1,
          n: 'KodeLife%202022-08-06%20at%2013.53.49%200000.png',
          g: '46',
          t: '@1x',
        },
        25: {
          p: 1,
          n: 'YellowDrawButton.svg',
          g: '68',
          t: 'image/svg+xml',
        },
        17: {
          p: 1,
          n: 'YellowFillButton.svg',
          g: '49',
          t: 'image/svg+xml',
        },
        26: {
          p: 1,
          n: 'RedDrawButton.svg',
          g: '70',
          t: 'image/svg+xml',
        },
        18: {
          p: 1,
          n: 'RedFillButton.svg',
          g: '51',
          t: 'image/svg+xml',
        },
        27: {
          p: 1,
          n: 'PurpleDrawButton.svg',
          g: '72',
          t: 'image/svg+xml',
        },
        19: {
          p: 1,
          n: 'PurpleFillButton.svg',
          g: '53',
          t: 'image/svg+xml',
        },
        28: {
          p: 1,
          n: 'OrangeDrawButton.svg',
          g: '74',
          t: 'image/svg+xml',
        },
        '-1': {
          n: 'PIE.htc',
        },
        29: {
          p: 1,
          n: 'GreenDrawButton.svg',
          g: '76',
          t: 'image/svg+xml',
        },
        '-2': {
          n: 'blank.gif',
        },
        10: {
          p: 1,
          n: 'OrangePaint.svg',
          g: '32',
          t: 'image/svg+xml',
        },
        0: {
          p: 1,
          n: 'UiFrame.svg',
          g: '7',
          t: 'image/svg+xml',
        },
        1: {
          p: 1,
          n: 'ConnectWalletButton.svg',
          g: '9',
          t: 'image/svg+xml',
        },
        11: {
          p: 1,
          n: 'YellowPaint.svg',
          g: '34',
          t: 'image/svg+xml',
        },
        2: {
          p: 1,
          n: 'MintButton.svg',
          g: '14',
          t: 'image/svg+xml',
        },
        20: {
          p: 1,
          n: 'OrangeFillButton.svg',
          g: '55',
          t: 'image/svg+xml',
        },
      },
      l,
      [],
      e,
      [
        {
          n: 'DePicUI',
          o: '1',
          X: [0],
        },
      ],
      [
        {
          o: '3',
          p: '600px',
          cA: false,
          Y: 1920,
          Z: 1080,
          L: [],
          c: '#FFF',
          bY: 1,
          d: 1920,
          U: {},
          T: {
            kTimelineDefaultIdentifier: {
              q: false,
              z: 0,
              i: 'kTimelineDefaultIdentifier',
              n: 'Main Timeline',
              a: [],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            '99',
            '83',
            '86',
            '84',
            '98',
            '100',
            '87',
            '119',
            '118',
            '117',
            '116',
            '115',
            '114',
            '113',
            '112',
            '88',
            '108',
            '107',
            '106',
            '102',
            '101',
            '105',
            '104',
            '103',
            '89',
            '110',
            '111',
            '85',
            '90',
            '109',
            '91',
            '92',
            '93',
            '94',
            '95',
            '96',
            '97',
          ],
          n: 'Untitled Layout',
          _: 0,
          v: {
            86: {
              h: '18',
              p: 'no-repeat',
              x: 'visible',
              a: 533,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 31,
              k: 'div',
              b: 148,
              d: 84,
              c: 179,
            },
            95: {
              h: '36',
              p: 'no-repeat',
              x: 'visible',
              a: 381,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 6,
              bF: '109',
              b: 0,
              d: 68,
              k: 'div',
              c: 65,
            },
            87: {
              h: '20',
              p: 'no-repeat',
              x: 'visible',
              a: 0,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 8,
              bF: '119',
              b: 0,
              d: 125,
              k: 'div',
              c: 126,
            },
            116: {
              h: '76',
              p: 'no-repeat',
              x: 'visible',
              a: 3,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 5,
              bF: '119',
              b: 2,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            96: {
              h: '38',
              p: 'no-repeat',
              x: 'visible',
              a: 458,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 7,
              bF: '109',
              b: 0,
              d: 68,
              k: 'div',
              c: 65,
            },
            103: {
              h: '53',
              p: 'no-repeat',
              x: 'visible',
              a: 8,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 3,
              bF: '108',
              b: 4,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            88: {
              h: '22',
              p: 'no-repeat',
              x: 'visible',
              a: 5,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 8,
              bF: '108',
              b: 2,
              d: 125,
              k: 'div',
              c: 126,
            },
            97: {
              h: '40',
              p: 'no-repeat',
              x: 'visible',
              a: 537,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 8,
              bF: '109',
              b: 0,
              d: 68,
              k: 'div',
              c: 65,
            },
            117: {
              h: '78',
              p: 'no-repeat',
              x: 'visible',
              a: 5,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 6,
              bF: '119',
              b: 2,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            89: {
              h: '24',
              p: 'no-repeat',
              x: 'visible',
              a: 0,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 2,
              bF: '111',
              b: 0,
              d: 128,
              aA: {
                a: [
                  {
                    p: 0,
                  },
                ],
              },
              k: 'div',
              c: 128,
              aP: 'pointer',
            },
            104: {
              h: '55',
              p: 'no-repeat',
              x: 'visible',
              a: 8,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 4,
              bF: '108',
              b: 5,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            98: {
              h: '42',
              p: 'no-repeat',
              x: 'visible',
              a: 533,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 30,
              k: 'div',
              b: 219,
              d: 87,
              c: 40,
            },
            110: {
              h: '65',
              p: 'no-repeat',
              x: 'visible',
              a: -4,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 1,
              bF: '111',
              b: 0,
              d: 132,
              k: 'div',
              c: 132,
            },
            99: {
              h: '46',
              p: 'no-repeat',
              x: 'visible',
              a: -34,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 2,
              k: 'div',
              b: -19,
              d: 1099,
              c: 1954,
            },
            118: {
              h: '80',
              p: 'no-repeat',
              x: 'visible',
              a: 2,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 7,
              bF: '119',
              b: 1,
              d: 123.17,
              k: 'div',
              c: 123.17,
            },
            105: {
              h: '57',
              p: 'no-repeat',
              x: 'visible',
              a: 8,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 5,
              bF: '108',
              b: 5,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            111: {
              k: 'div',
              x: 'visible',
              c: 128,
              d: 128,
              z: 18,
              a: 483,
              j: 'absolute',
              b: 586,
            },
            119: {
              k: 'div',
              x: 'visible',
              c: 126.17,
              d: 125,
              z: 7,
              a: 483,
              j: 'absolute',
              b: 304,
            },
            106: {
              h: '59',
              p: 'no-repeat',
              x: 'visible',
              a: 6,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 6,
              bF: '108',
              b: 4,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            112: {
              h: '68',
              p: 'no-repeat',
              x: 'visible',
              a: 5,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 1,
              bF: '119',
              b: 2,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            107: {
              h: '61',
              p: 'no-repeat',
              x: 'visible',
              a: 6,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 7,
              bF: '108',
              b: 4,
              d: 123.17,
              k: 'div',
              c: 123.17,
            },
            90: {
              h: '26',
              p: 'no-repeat',
              x: 'visible',
              a: 0,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 1,
              bF: '109',
              b: 0,
              d: 68,
              k: 'div',
              c: 65,
              aP: 'pointer',
            },
            113: {
              h: '70',
              p: 'no-repeat',
              x: 'visible',
              a: 5,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 2,
              bF: '119',
              b: 2,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            100: {
              c: 617,
              d: 525,
              I: 'Solid',
              J: 'Solid',
              K: 'Solid',
              g: '#F6FCFF',
              L: 'Solid',
              M: 1,
              N: 1,
              A: '#D8DDE4',
              x: 'visible',
              j: 'absolute',
              B: '#D8DDE4',
              P: 1,
              k: 'div',
              C: '#D8DDE4',
              z: 3,
              O: 1,
              D: '#D8DDE4',
              a: 631,
              b: 277,
            },
            108: {
              k: 'div',
              x: 'visible',
              c: 137,
              d: 128,
              z: 6,
              a: 478,
              j: 'absolute',
              b: 442,
            },
            91: {
              h: '28',
              p: 'no-repeat',
              x: 'visible',
              a: 77,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 2,
              bF: '109',
              b: 0,
              d: 67,
              k: 'div',
              c: 64,
            },
            83: {
              h: '7',
              p: 'no-repeat',
              x: 'visible',
              a: 510,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 4,
              k: 'div',
              b: 125,
              d: 844,
              c: 916,
            },
            92: {
              h: '30',
              p: 'no-repeat',
              x: 'visible',
              a: 152,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 3,
              bF: '109',
              b: 0,
              d: 68,
              k: 'div',
              c: 65,
            },
            114: {
              h: '72',
              p: 'no-repeat',
              x: 'visible',
              a: 5,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 3,
              bF: '119',
              b: 2,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            101: {
              h: '49',
              p: 'no-repeat',
              x: 'visible',
              a: 6,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 1,
              bF: '108',
              b: 4,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            109: {
              k: 'div',
              x: 'visible',
              c: 598,
              d: 68,
              z: 5,
              a: 609,
              j: 'absolute',
              b: 820,
            },
            93: {
              h: '32',
              p: 'no-repeat',
              x: 'visible',
              a: 230,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 4,
              bF: '109',
              b: 0,
              d: 67,
              k: 'div',
              c: 64,
            },
            84: {
              h: '9',
              p: 'no-repeat',
              x: 'visible',
              a: 1028,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 21,
              k: 'div',
              b: 148,
              d: 113,
              c: 255,
            },
            85: {
              h: '14',
              p: 'no-repeat',
              x: 'visible',
              a: 1234,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 20,
              k: 'div',
              b: 776,
              d: 191,
              c: 191,
              aP: 'pointer',
            },
            115: {
              h: '74',
              p: 'no-repeat',
              x: 'visible',
              a: 5,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 4,
              bF: '119',
              b: 2,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
            94: {
              h: '34',
              p: 'no-repeat',
              x: 'visible',
              a: 306,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'inline',
              z: 5,
              bF: '109',
              b: 0,
              d: 68,
              k: 'div',
              c: 65,
            },
            102: {
              h: '51',
              p: 'no-repeat',
              x: 'visible',
              a: 6,
              dB: 'img',
              q: '100% 100%',
              j: 'absolute',
              r: 'none',
              z: 2,
              bF: '108',
              b: 5,
              d: 121.17,
              k: 'div',
              c: 121.17,
            },
          },
        },
      ],
      {},
      h,
      {},
      null,
      false,
      true,
      -1,
      true,
      true,
      false,
      true,
      true
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute('HYP_dn', f);
    c.z_o(this.body);
  })();
})();
